### ISSUE TITLE
ASAP HELP - How to Link JADE with MySQL and HTML?

### ISSUE THREAD

**Issue by Anisha194** [ubenzer/involve#1]
Hi.

Hope your all well.

I'm in my final year of my degree and I have chosen to do my final year project on JADE. I am having difficulties linking my jade agent to a website as well as to a database. I've been working through the book - Developing Multi-Agent Systems with JADE and i still cant seem to find my answer.

Is there any possible way of linking JADE with MySQL and HTML?

If you could please get back to me ASAP that would be excellent as i do have a deadline set for 21/04/2017 to hand this in.

Thankyou

**Comment by ubenzer** [comment]
Hello @Anisha194 I didn't use JADE for a while and I don't think I can be helpful in anyway. I have [this](https://github.com/ubenzer/Agent-Based-Programming-Experiments-with-JADE) project from a few years ago but it has nothing to do with the things you asked.
